apiVersion: batch/v1
kind: Job
metadata:
  name: paranoia-kspm
spec:
  template:
    spec:
      containers:
      - name: paranoia-kspm-pod
        image: rodriguezsr429/paranoia:0.0.3
        command: ["./paranoia"]
        args: ["rbac", "-b"]
        env:
        - name: KUBECONFIG
          value: /etc/kubeconfig/config
        volumeMounts:
        - name: kubeconfig
          mountPath: /etc/kubeconfig
          readOnly: true
      volumes:
      - name: kubeconfig
        secret:
          secretName: kubeconfig
      restartPolicy: Never
  backoffLimit: 4